### ISSUE TITLE
Error: Cannot find module './middleware/viewer'

### ISSUE THREAD

**Issue by Flo2315** [windicss/nuxt-windicss-module#1]
Hi loonpwn,

Thank you for this module.

However I have a problem with tailwind css viewer.

My error:
<img width="703" alt="Capture d’écran 2021-03-08 à 12 33 02" src="https://user-images.githubusercontent.com/7684148/110326487-0157c880-8019-11eb-813c-d6aa03b7b224.png">

You have an idea ?

Thx 🙏

**Comment by loonpwn** [comment]
Hey @Flo2315 

Could you please make sure you're using the latest version of the package, version 0.2.0.

The middleware has been removed as windi doesn't support it out of the box

**Comment by Flo2315** [comment]
Yes it works now.
Thank you @loonpwn
