### ISSUE TITLE
postcss warnings on local dev environment

### ISSUE THREAD

**Issue by liyasthomas** [windicss/nuxt-windicss-module#104]
**Describe the bug**
Getting multiple warning messages thrown from `postcss` while running the latest nuxt-windicss-module.

```base
WARN  You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
```

**To Reproduce**
1. Install `nuxt-windicss-module` in any nuxt project
2. Run `npm run dev` to start local dev environment
3. See error

**Expected behavior**
This behavior/warning message thrown from `postcss` can be turned off. Refer discussion in postcss repo here: https://github.com/postcss/postcss/issues/1375

**Screenshots**
<img width="1091" alt="Screenshot 2021-06-28 at 4 44 54 PM" src="https://user-images.githubusercontent.com/10395817/123628191-70f3fc80-d830-11eb-9d64-714770299ee3.png">

**Additional context**
I migrated from TailwindCSS to WindiCSS and removed postcss dependency - so this might be exactly coming from windicss module deps.

**Comment by harlan-zw** [comment]
Hey @liyasthomas 

Thanks for the issue. The latest release https://github.com/windicss/nuxt-windicss-module/releases/tag/1.1.3 should fix it. I'm not exactly sure how you disabled postcss though

Feel free to re-open if that's not the case
