### ISSUE TITLE
Hot-reload does not work

### ISSUE THREAD

**Issue by MasterEros** [windicss/nuxt-windicss-module#108]
Hello.
I've been struggling with windicss problem for a month now.
Hot-reload doesn't work with nuxt js.
All configuration is in windi.config.js.
In custom nuxt, empty config.
With the same build, tailwind supported hot development, without constantly reloading the page when the file was updated.

**Comment by harlan-zw** [comment]
Hey @MasterEros 

Sorry you're having issues. Can you ideally share a reproduction repo otherwise please paste your configs and I'll try and repl

**Comment by harlan-zw** [comment]
@MasterEros 

This may possibly be fixed with 1.1.3 but impossible to know without your config. Will close for now, please feel free to open with your configs if the updated version doesn't work

**Comment by MasterEros** [comment]
Hello.

I think the question can be closed.

I don't know exactly how, but I tried to think and poke.

The problem was solved in several possible ways:
- In build modules, you need to put nuxt-windicss closer / to the left than nuxt-build-optimisations and @ nuxtjs / svg-sprite
- Changed include in windi.config.js to ["** / *. {vue, js}", "** / ** / *. {vue, js}"]
- Disabled transformCSS: "pre" in windi.config.js
- Disabled cache in nuxt.build
- Added dev: process.env.NODE_ENV! == "production" to nuxt.config.js properties
