### ISSUE TITLE
[suggestion] rename npm package to nuxt-windicss

### ISSUE THREAD

**Issue by pi0** [windicss/nuxt-windicss-module#11]
Hi! Thanks for this amazing module. I've a small suggestion to rename npm package from `nuxt-windicss-module` to `nuxt-windicss` to be consistent with 3rd party module naming convention.

**Comment by loonpwn** [comment]
Hey @pi0, thanks for this suggestion. I think it's a great idea and I've gone ahead and updated the name to `nuxt-windicss`.

I'll keep the github repo name the same to add clarity.
