### ISSUE TITLE
Module leads to global SASS files being ignored.

### ISSUE THREAD

**Issue by skizer** [windicss/nuxt-windicss-module#114]
**Describe the bug**
Using the nuxt-windicss-module within a nuxt project, leads to SASS files being ignored.
Changing the order of css files loaded via virtual entries at the nuxt.config.js css property doesn't solve it.
SCSS files are working fine tho.

**To Reproduce**
1. Setup nuxt, add the nuxt-windicss-module. (Ether automated, or separated - tested both)
2. Add a global sass file via nuxt.config.js

**Version**
**Nuxt:** 2.15.7
**nuxt-windicss-module:** 1.2.3

**Comment by harlan-zw** [comment]
Hey @skizer 

Thanks for the issue. Should be fixed in 1.4.6, seems like the core package can no longer process sass files. So you won't be able to use @apply in that file.

Let me know if you still have issues :)

**Comment by ColinEspinas** [comment]
Do you have updates on this issue? It looks like we still can't use `@apply` with SASS files.

**Comment by AntonAleikin** [comment]
Have the same issue too. 
Classes with @apply are ignored in global SASS files. 
At the same time it seems that @apply works in global CSS files.
