### ISSUE TITLE
Failing with Nuxt 3: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by atinux** [windicss/nuxt-windicss-module#118]
**Describe the bug**
Nuxt WindiCSS does not work with Nuxt 3.

**To Reproduce**
Checkout the reproduction sandbox:
https://codesandbox.io/s/lingering-water-bbiem?file=/app.vue

**Expected behavior**
Should work 😄 

**Screenshots**
<img width="607" alt="Screenshot 2021-10-12 at 14 01 02@2x" src="https://user-images.githubusercontent.com/904724/136952325-51a2ccb9-fdf6-4dd7-8543-5217f53afda9.png">

**Additional context**
Error seems related to `jiti`, I believe @antfu may have some clue about this 🤞

**Comment by pi0** [comment]
Can you please try recreation lockfile to get jiti@1.12.7 update?
