### ISSUE TITLE
[vite] avoid depending on buildModules existence

### ISSUE THREAD

**Issue by pi0** [windicss/nuxt-windicss-module#12]
Ref: #5

It should be strictly avoided to depend on `nuxt-vite` existence to detect _viteMode_ and only using hooks since module name can change and it is not same condition for nuxt3. (PS: It is masked now with `nuxt-vite@30` so module will be broken with 29+)

**Comment by loonpwn** [comment]
Hey @pi0. Hope you are well and thanks for the issue. I have merged @danielroe's updated code which has addressed this.
