### ISSUE TITLE
DeprecationWarning: Use of deprecated folder mapping

### ISSUE THREAD

**Issue by shadear** [windicss/nuxt-windicss-module#122]
**Describe the bug**
```
ERROR  (node:62280) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /home/shadear/Projects/local/web/nuxt3-app/node_modules/nuxt-windicss/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**To Reproduce**
1. Add nuxt-windicss module to nuxt 3
2. Run 'npm run dev'
3. See error.

**Expected behavior**
Should work without giving error

**Additional context**
Related issues:
[Postcss](https://github.com/postcss/postcss/issues/1455)
[Vuex](https://github.com/vuejs/vuex/issues/2071)

**Temp fix**
Change `"./": "./",` to `"./*": "./*",`
https://github.com/windicss/nuxt-windicss-module/blob/b532838b0973aca54d6df5d506a3263efac6bc5f/package.json#L24

**Comment by harlan-zw** [comment]
Hey @shadear 

Thanks for the issue. This is fixed in v2 :) 

https://github.com/windicss/nuxt-windicss-module/releases/tag/2.0.0
