### ISSUE TITLE
Change Repo name to nuxt-windicss

### ISSUE THREAD

**Issue by HenrijsS** [windicss/nuxt-windicss-module#125]
I submitted a pull request to the windicss docs to reference the new NPM package but noticed that the github and npm names differ so there's a compatability issue.
https://github.com/windicss/docs/pull/133

I suggest to change the Repo name to the one in NPM so there isn't any confusion.
But also, why is there 2 packages in NPM for the module?

**Comment by harlan-zw** [comment]
Hey @HenrijsS 

Thanks for the suggestion. The name includes the module suffix in GitHub as it's consistent with a lot of the other community modules, see here: https://github.com/nuxt/framework/discussions/751#discussioncomment-1481994

Originally the npm package also included this suffix, but with feedback from the Nuxt team they suggested omitting it there. 

I do see the issue having this inconsistency creates on the doc site though, so not too sure what to do about it

**Comment by HenrijsS** [comment]
Also they merged my PR, which I said not to. And now the GitHub link leads to a 404.
https://github.com/windicss/docs/pull/133
