### ISSUE TITLE
windicss and sass doesn't work

### ISSUE THREAD

**Issue by Flo2315** [windicss/nuxt-windicss-module#13]
Hello @loonpwn ,

My project uses lang sass inside components, but nothing is compiled anymore.

Exemple code:
```
<style lang="sass">
.container
  display: flex
  @apply bg-gray-500
</style>
```

The package is compatible with sass ?

Have a good day,
Florian

**Comment by loonpwn** [comment]
Hey @Flo2315 

Thanks for making an issue. I looked into it and for now, there is only support for these directives in scss, css and postcss. I plan to fix this at some point soon but it is a bit complex.

Please update to the latest in the meantime to fix your sass

**Comment by productfrontenddeveloper** [comment]
@loonpwn dont fix

![Screen Shot 2021-03-11 at 06 21 34](https://user-images.githubusercontent.com/38668796/110730730-08a5ee80-8232-11eb-8946-8872959d51f1.png)

```
<style scoped>
.body {
  @apply bg-gray-100
}
</style>
``` 
"nuxt-windicss": "0.3.1",
"nuxt": "2.15.3",

**Comment by Flo2315** [comment]
Hi @loonpwn 

Thank, now the sass is well compiled but the @apply directive is not.

The problem will not come directly from the windicss module ?

**Comment by Flo2315** [comment]
Only CSS doesn't work either

```
<style>
.container {
  text-align-center;
  @apply bg-gray-500;
}
</style>
```

<img width="209" alt="Capture d’écran 2021-03-12 à 21 15 36" src="https://user-images.githubusercontent.com/7684148/110993852-24b3a800-8378-11eb-8120-938fd90ee3e5.png">


"nuxt-windicss": "0.3.1",
"nuxt": "2.14.12",

**Comment by productfrontenddeveloper** [comment]
@loonpwn hmm fixed thank you, beacuse 

@Flo2315 
@apply dont used css with example

```
<style scoped lang="scss">
.body {
  @apply bg-gray-100;
}
</style>
```

**Comment by loonpwn** [comment]
Hey @Flo2315 

Thanks for your patience on this one. The sass won't still work and will be addressed in a future update, however the plain scoped css should be working with the latest version (0.4.0)

I have this code doing what it's supposed to:

```vue
<template>
  <div class="body">
    <Nuxt />
  </div>
</template>
<style scoped>
.body {
  @apply bg-gray-100
}
</style>
```

**Comment by harlan-zw** [comment]
SASS is now supported in version 0.7.1 :) 

Example:

```
<template>
  <div class="sass">
    <h2>SASS scoped</h2>
    orange-400 -> orange-900
  </div>
</template>
<style lang="sass" scoped>
.sass
  @apply bg-orange-400 text-white p-4 w-1/4 transition hover:(bg-orange-900 text-orange-100)
  h2
    @apply font-bold text-sm
</style>
```

cc: @Flo2315  @productfrontenddeveloper 

Going to close this off, let me know if you have any issues.
