### ISSUE TITLE
[Nuxt 3] Can't resolve './@windicss/windi-base.css'

### ISSUE THREAD

**Issue by Blemming** [windicss/nuxt-windicss-module#131]
**Describe the bug**
When starting nuxt 3 project I get this error
```
Cannot start nuxt:  Can't resolve './@windicss/windi-base.css' in ...
```

**To Reproduce**
`npx nuxi init test-project`
`cd test-project`
`yarn add nuxt-windicss`
add to nuxt config:
```
buildModules: [
'nuxt-windicss',
],
``` 
`yarn install`
`yarn dev`

**Expected behavior**
Nuxt should start

**Screenshots**
![image](https://user-images.githubusercontent.com/12241815/138148039-0ccadc9b-1e35-48c0-98f6-3a075ac86ceb.png)

**Additional context**
Windows, with yarn
`Nuxt CLI v3.0.0-27245590.7c3b488 `

**Comment by samelie** [comment]
yeah same here `Cannot restart nuxt:  Can't resolve './@windicss/windi.css' in '/Users/`  , this version works `3.0.0-27244261.c49f9ca`
