### ISSUE TITLE
Scanning third-party code from node_modules

### ISSUE THREAD

**Issue by mercs600** [windicss/nuxt-windicss-module#14]
I think is related with https://github.com/windicss/vite-plugin-windicss/issues/76

So, it doesn't work when I want to add dirs to scan by third-party nuxt module.

```js
const contentToPurge = [
  resolve(__dirname, '../components/'),
  resolve(__dirname, '../directives/')
]

  this.nuxt.hook('windicss:config', function (config) {
    config.scan.dirs = [...config.scan.dirs, ...contentToPurge]
  })
```

it works ideally with tailwind module.

**Comment by loonpwn** [comment]
Hey @mercs600, thanks for making an issue :)

Assuming that content to purge lives in a node_module then it won't work at the moment, waiting for a fix to be merged into the base package. Will let you know once it should be working

**Comment by harlan-zw** [comment]
Hey @mercs600 

Sorry for the delay, there's a work around in the read me now for this behaviour: https://github.com/windicss/nuxt-windicss-module#scan-classes-from-a-node_modules-package

Let me know if you have any issues, will close this for now.
