### ISSUE TITLE
Preflight issue

### ISSUE THREAD

**Issue by paulvonber** [windicss/nuxt-windicss-module#20]
Hey guys, I tried to migrate to WindiCSS on Nuxt and seems it does the job, build speed looks amazing and really fast, but I have one issue with preflight in tailwind.config.js it was easy to disable it as simple as this:
` 
corePlugins: {
    preflight: false
  }
` 
but seems that it does not work with windi, I'm not sure if I'm doing something wrong or it's not yet implemented.

Thanks for the help in advance.

**Comment by schelmo** [comment]
does
in your nuxt.config.js:
export default {
  windicss: {
    preflight: false
  }
work?

**Comment by paulvonber** [comment]
@schelmo ah yes this way it works! Thanks a lot!

**Comment by loonpwn** [comment]
Thanks for helping out @schelmo. 

Looks like you have it sorted @paulvonber so I'll close this. I have added an example of this configuration to the readme for if someone else gets stuck on it.
