### ISSUE TITLE
Updating the docs

### ISSUE THREAD

**Issue by Atinux** [windicss/nuxt-windicss-module#23]
I think we could remove this part: https://windicss.org/guide/vue.html#nuxt

And add a Nuxt page, what do you think?

**Comment by loonpwn** [comment]
Thanks for the suggestion @Atinux :)

There is a complete rebuild of the doc site going on and looks like that has already been sorted, see: https://next.windicss.org/guide/integrations/vue-cli.html 

It's also on `next` branch within the docs repo if you're curious.
