### ISSUE TITLE
Wrong hook name

### ISSUE THREAD

**Issue by Atinux** [windicss/nuxt-windicss-module#3]
https://github.com/windicss/nuxt-windicss-module/blob/1463cbdbe4007e25cf2f1d0f0e76fe8b22150fea/src/index.ts#L36

Nice work BTW :)

**Comment by loonpwn** [comment]
Thanks @Atinux :)  Always good to have a second pair of eyes for those silly mistakes.

Have fixed it and updated the readme for using the hook.
