### ISSUE TITLE
Error: Module build failed: Expected an opening square bracket

### ISSUE THREAD

**Issue by stefan-galescu** [windicss/nuxt-windicss-module#7]
```
Module build failed (from ./node_modules/css-loader/dist/cjs.js): CssSyntaxError (3173:26) /Development/nuxt-windicss-demo/@virtual/windi.css Expected an opening square bracket. [90m 3171 | [39m --tw-ring-opacity[33m:[39m 0.5[33m;[39m [90m 3172 | [39m[33m}[39m [1m[31m>[39m[22m[90m 3173 | [39m[33m.dark[39m [33m.dark[39m\[focus-within[33m][39m\:border-brand-400[33m[[39mfocus-within[33m][39m [33m{[39m [90m | [39m [1m[31m^[39m[22m [90m 3174 | [39m --tw-border-opacity[33m:[39m 1[33m;[39m [90m 3175 | [39m border-color[33m:[39m [36mrgba[39m[36m([39m251, 191, 36, [36mvar[39m[36m(--tw-border-opacity)[39m[36m)[39m[33m;[39m
```

What other info can I provide to help here?

**Comment by stefan-galescu** [comment]
Hi @loonpwn!

Thanks for getting back on this. I took a look at `nuxt.config.js` and after removing stuff one by one, I found the culprit. It was due to this property:

```js
// nuxt.config.js
{
  build: {
    extractCss: true,
  },
}
```

After removing it, everything started working normally.

**Comment by loonpwn** [comment]
Good catch @stefan-galescu. I'll keep this open to investigate why that may be causing an issue

**Comment by stefan-galescu** [comment]
That’s great! Thank you for looking into it!

**Comment by harlan-zw** [comment]
This doesn't seem to be an issue with the latest nuxt, at least as far as I can tell.

Also, the actual config value is 
```
 build: {
    extractCSS: true,
  },
```

Note that the CSS is capitalised, so not sure if this was due to something else. 

Will close this off for now
