### ISSUE TITLE
can't use filters plugin

### ISSUE THREAD

**Issue by chrislutw** [windicss/nuxt-windicss-module#83]
**Describe the bug**
open nuxt project and run nuxt command
with error message: 
segmentation fault (core dumped)
error Command failed with exit code 139.

nuxt: 2.15.4
nuxt-windicss: 0.7.1

**To Reproduce**
1. open https://codesandbox.io/s/mystifying-cloud-m65mf?file=/windi.config.js
2. restart sandbox
3. See error

**Comment by chrislutw** [comment]
version: 0.6.0 has same problem

**Comment by chrislutw** [comment]
## Describe the bug
And can't see filters working. 

setting with this config

```js
import { defineConfig } from "windicss/helpers";

export default defineConfig({
  plugins: [require("windicss/plugin/filters")]
});
```
and give img element class

```
<img class="filter grayscale w-full h-20" />
```
![image](https://user-images.githubusercontent.com/18047748/117431824-3ff7f980-af5c-11eb-8370-166f8aad61f0.png)

can't see windi generated class in virtual:windi.css

nuxt: 2.15.4
nuxt-windicss: 0.5.4

## To Reproduce
Steps to reproduce the behavior:

1. open https://codesandbox.io/s/awesome-smoke-n9xdk?file=/pages/index.vue
2. restart sandbox
3. See error

**Comment by harlan-zw** [comment]
Hey @chrislutw, the `filters` is only available in windi v3, if you'd like to use that please use the next tag until we do an official release.

`yarn add -D nuxt-windicss@next`

Let me know if you have any issues with that
