### ISSUE TITLE
Some node_modules files aren't parsed since 0.7.x

### ISSUE THREAD

**Issue by Tahul** [windicss/nuxt-windicss-module#87]
Seems like WindiCSS breaks Nuxt PostCSS support and/or does not parse files correctly using latest versions.

Only happens when files are nested into node_modules.

We discussed this with @harlan-zw via Discord.

Reproduction:
https://github.com/Tahul/image

This repository uses 0.5.4.

Try using this into `image/docs/package.json`:

```json
  "resolutions": {
    "nuxt-windicss": "0.8.0-2" // or 0.7.x
  }
```

**Comment by harlan-zw** [comment]
Workaround is now in the documentation , thanks

**Comment by harlan-zw** [comment]
@Tahul Could you provide some more details on what's not being processed :pray:

**Comment by harlan-zw** [comment]
Going to close, discussions are on discord. If there's still issues we should open a new issue with exact issue
