### ISSUE TITLE
Compatibility with nuxt content

### ISSUE THREAD

**Issue by haztecaso** [windicss/nuxt-windicss-module#88]
I'm using the content module with some html inside the markdown files and I'd love to use windi classes there.
Right now the classes are included only when I run `nuxt generate` but not when I'm in `nuxt dev` mode so I cant see the changes live when I'm editing the content. Is it there any hook or option to scan the classes inside the markdown files in the content directory?

I dont understand fully how windicss module works but if I'm not mistaken I think that it needs a rebuild for including new classes. Maybe one partial solution would be to include all default windicss classes into dev mode. The only flaw I see with this approach is that it would not work with auto-inferred values. Maybe in this case I could try to detect this classes and target a rebuild.

Thanks in advance and sorry if I'm not posting this issue in the right place or format (It's the first issue that I open in github).

**Comment by harlan-zw** [comment]
Hey @haztecaso, thanks for the issue :)

I have fixed this in 0.7.5, please upgrade and let me know if you have any issues
