### ISSUE TITLE
Add support for @layer base styles

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [windicss/nuxt-windicss-module#93]
**Is your feature request related to a problem? Please describe.**
TailwindCSS allows to specify base layer styles in external css/pcss file which will compile before **components** and **utilities**. 
Why is it important to have such feature? Imagine a website that has base styles in external css  files along with WindiCSS styles  for different reasons, such as migrating to Windi or usage of LESS/SASS of some other CSS lib, or just having a way to specify base styles in usual css like syntax (not using config)

**Describe the solution you'd like**
https://tailwindcss.com/docs/adding-base-styles#using-css

**Describe alternatives you've considered**
An alternative would be a use of config, but it's not as convenient as plain CSS for base styles

**Additional context**
I would suggest having a property inside nuxt.config windicss object that would allow to specify base styles array of files without a need to create explicit tailwind.css file. It could look something like this:
nuxt.config.js
```
...
windicss: {
    base: ['./assets/css/base1', './assets/css/base2']
  }
...
```

**Comment by AndrewBogdanovTSS** [comment]
@harlan-zw is this PR covers only vite plugin functionality? Will it also be available for webpack based build?

**Comment by harlan-zw** [comment]
Hey @AndrewBogdanovTSS 

The vite and webpack plugin both use the same underlying util package so they share a lot of functionality.

I've also just released the layout ordering feature (https://windicss.org/integrations/webpack.html#layers-ordering) which you can use to achieve what you're after

Let me know if you have any questions

**Comment by AndrewBogdanovTSS** [comment]
@harlan-zw this issue is not about .pcss file support. The only solution I see is using `@layer base` inside of the css file (.pcss is not currently supported from what I understand). 
AFAIU you don't want to also support `base` property for windicss config as I initially suggested?
