### ISSUE TITLE
[vite] Internal server error: /@windicss/windi.css: Unclosed bracket

### ISSUE THREAD

**Issue by eggsy** [windicss/nuxt-windicss-module#94]
**Describe the bug**
Seems like it's trying to compile a class named `.ring`, but I don't have that class for a while now, so it's gone. I don't know what the issue is, I'm using `nuxt-vite` and my repository is `[eggsy/website](https://github.com/eggsy/website)`.

**To Reproduce**
1. Clone repository "[eggsy/website](https://github.com/eggsy/website)"
2. Run it in dev mode (remove all .ring classes if you really want to make sure)
3. Try to visit the site

**Expected behavior**
Should have built all classes with no issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/13917975/120118148-c9849b00-c199-11eb-8fd2-0d6f8bf5d6b3.png)

**Additional context**
I tried clearing cache, upgrading modules and making sure that I don't have a `.ring`. I still have one on my repo, I remove it completely to see if it was the real problem, no luck, it didn't work, it still said `.ring` had problems.

**Comment by harlan-zw** [comment]
Hey @eggsy 

Sorry about that, seems like it was an issue with the windi vite plugin. I've done a release with it updated which seems like it has fixed the issue.
