### ISSUE TITLE
.pcss files are ignored from the compilation although extract is specified

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [windicss/nuxt-windicss-module#95]
**Describe the bug**
.pcss files are ignored from the compilation although extract is specified

**To Reproduce**

1. Go to this repository https://codesandbox.io/s/stupefied-bird-qyvqv?file=/assets/style/index.pcss
2. Inspect page and see that @apply styles from index.pcss file are not compiling 
![image](https://user-images.githubusercontent.com/2766448/120622104-2f597700-c467-11eb-879d-8e7e8b6496ee.png)

**Expected behavior**

@apply should work inside .pcss files along with other .pcss plugins installed such as postcss-import or postcss-nested

**Additional context**

In tailwind there is a way to control that compilation ordering via nuxt postcss property, like so:
```
postcss: {
    plugins: {
      'postcss-import': {},
      tailwindcss: {},
      'postcss-nested': {},
    }
  },
```
but for Windi I haven't seen anything like that described in docs, just changing tailwindcss with windicss in that array doesn't do the trick

**Comment by harlan-zw** [comment]
Hey @AndrewBogdanovTSS 

Is this still an issue for the latest version, 1.0.3?

**Comment by AndrewBogdanovTSS** [comment]
@harlan-zw yes, it's still the same. I tried it with the latest v. 1.0.4 and got the same failed results as before both for the nuxt-windicss module and the vite plugin. You can check the updated repo for actual reproduction:  https://codesandbox.io/s/stupefied-bird-qyvqv?file=/assets/style/index.pcss

**Comment by harlan-zw** [comment]
Hey @AndrewBogdanovTSS 

Replicated your issue and this PR should sort it https://github.com/windicss/nuxt-windicss-module/issues/95

**Comment by harlan-zw** [comment]
@AndrewBogdanovTSS  Issue seems to be fixed. You did have a configuration bug in the nuxt.config.js, I have a working example here: https://codesandbox.io/s/polished-feather-143b9?file=/windi.config.ts

Closing this off, let me know if you have any further issues.

**Comment by AndrewBogdanovTSS** [comment]
Hi @harlan-zw. Thanks for the repo example, I also checked it with Vite plugin and it also works well even "by default", without any extra configuration which is even better, thanks a lot for the fix 👍

**Comment by AndrewBogdanovTSS** [comment]
@harlan-zw one issue I noticed after some testing that I can't use @layer base utilities in external .pcss file, although regular postcss syntax works fine. For example:
This works fine:
```
.my {
    &-container {
      @apply max-w-90 bg-green-100 mx-auto;
    }
  }
```
this produces an warning:
```Module Warning (from ./node_modules/postcss-loader/src/index.js): 
friendly-errors Warning
....\layout.pcss is empty```
```
@layer base {
  .my {
    &-container {
      @apply max-w-90 bg-green-100 mx-auto;
    }
  }
}
```
for some reason I can't replicate it in sandbox environment, only happens to me locally. But maybe you also will stumble upon it 🤷‍♂️
