### ISSUE TITLE
Cause the @nuxt/content *.json file to be unusable

### ISSUE THREAD

**Issue by chrislutw** [windicss/nuxt-windicss-module#96]
**Describe the bug**
Could not parse or query @nuxt/content *.json files

**To Reproduce**
1. visit https://codesandbox.io/s/nuxt-windi-m65mf
2. See error

**Expected behavior**
@nuxt/content .json files can be parse or query

**Screenshots**
![image](https://user-images.githubusercontent.com/18047748/121161727-dd0dc100-c87f-11eb-8685-4667b9ca5f3d.png)

**Additional context**
version:
nuxt: 2.15.14
@nuxt/content: 1.14.0
nuxt/windicss: 1.0.0

**Comment by arpadgabor** [comment]
Experiencing the same problem, happens to yaml files too.

```
Could not parse ./content/sections.yml: can not read a block mapping entry; a multiline key may not be an implicit key (32:1)

 29 | /* windicss layer components */
 30 | 
 31 | /* windicss layer utilities */< ...
```

**Comment by arpadgabor** [comment]
Looking at what the `/_content` endpoint returns, it seems like windicss appends these lines to the end of a file.

![image](https://user-images.githubusercontent.com/9270494/121704384-65889d80-cadc-11eb-9bdc-820484144e1d.png)

**Comment by arpadgabor** [comment]
Apparently this line from https://github.com/windicss/nuxt-windicss-module/commit/1c8021d06c51ccdb438a4e28311d7a1c938f69bd is not present in the last release.

https://github.com/windicss/nuxt-windicss-module/blob/d762799113c4691bde5c9338f8f600719dd11b54/src/index.ts#L118

Maybe @harlan-zw can help?

**Comment by harlan-zw** [comment]
Hey @arpadgabor 

Thanks for looking into this bug. Seems like there was a problem with the build for release 1.0.0, can you try with 1.0.3 and let me know if you still have issues

**Comment by arpadgabor** [comment]
Hello @harlan-zw ! Yes it does indeed work (1.0.1+), thanks for looking into it!

**Comment by chrislutw** [comment]
@arpadgabor @harlan-zw Thanks for help, can use windicss 3.1 new features in my project finally

**Comment by harlan-zw** [comment]
Thanks for making the issue @chrislutw and apologies for the delay.
