### ISSUE TITLE
increased memory usage from version 0.7.5 to 1.0.0

### ISSUE THREAD

**Issue by flavionn** [windicss/nuxt-windicss-module#97]
Hello, thanks for this module!

When I update from 0.7.5 to 1.0.0 and run `pnpm dev`

Memory usage jumps from 120 MB to 970 MB

Is this the expected behavior? If is I go back to 0.7.5.

I am worried about this because I dont have so much memory in my computer.

I'm using Nuxt 2.15.6, Nuxt Vite 0.1.1, Node 14.16.0

**Comment by harlan-zw** [comment]
Hey @flavionn 

This is quite alarming, can you try to upgrade and see if it's still an issue?

If it is then I might need to forward this to the vite windi plugin as an issue, as the webpack edition seems to be using a stable amount of memory

**Comment by flavionn** [comment]
thanks for the answer

the increase in memory usage still persists even when upgrading to version 1.0.3

**Comment by harlan-zw** [comment]
@flavionn Might be a bit hard for me to debug this, can you first check that any large folders (.git, node_modules, etc) are excluded from the scan config.

It's possible that the newer version isn't ignoring a folder that the previous one did.

If that doesn't solve anything, can you share your configs and I'll see if I can find anything

**Comment by flavionn** [comment]
Hey @harlan-zw thanks for support!

It's weird but after upgrading to version 1.0.6 (from 0.7.5) when I run `pnpm dev` the startup is slower, the memory usage goes to 1 GB, and sometimes stay in 1 GB and another times return to 150 MB. It's totally random. I don't know if it's something with my SO (Linux). On 0.7.5 everything runs much faster to me.

I don't have large folders that need to be excluded from scanning.

**windi.config.js**

```js
module.exports = {
  theme: {
    extend: {
      fontFamily: {
        sans: 'Inter, ui-sans-serif, system-ui'
      }
    }
  }
}

```

in **nuxt.config.js** I have:

```js
buildModules: [
  '@nuxtjs/google-analytics',
  '@nuxtjs/google-fonts',
  '@nuxtjs/localforage',
  'nuxt-vite',
  'nuxt-windicss'
],
```

**Comment by harlan-zw** [comment]
Hey @flavionn 

I tried to replicate this and ran into the same thing. At one point it was running and using 1gb of ram and I thought I was making some progress debugging it, then I restarted and it was using 150mb...

If you can figure out a way to reliability replicate the 1gb of ram usage then I can take a further look, others not much I can do for now sorry
